spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false

mybatis-plus:
  type-aliases-package: com.background.userService.domain
# ????????mapper????, ??????????????????????
# mapper-locations: classpath:/mappers/**/*.xml

# ??JWT????
security:
  jwt:
    token:
      secret-key: "s3cr3t!Key$1234_abCD+EfGhIjkLmN%&OpQrSt"
      expire-length: 3600000
